name: CI/CD (Docker → GHCR → Azure)

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: ghcr.io/nicop1709/p07---sentiment-analysis-prod

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=c1917757-cf99-490f-83d4-567865896547;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/;ApplicationId=14815754-6985-45bf-a851-10f0ffb19ca1"
      MODEL_VERSION: "ci"
      MODEL_DIR: "./models/savedmodel"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: pip-${{ runner.os }}-
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          python -m spacy download en_core_web_sm
      - name: Run tests
        run: pytest -q

  build_push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 🧱 Pousse deux tags: latest + SHA (complet)
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build_push
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App (container)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          # ⚠️ Déploie le SHA (déterministe) — et SURTOUT en minuscules
          images: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          # ⚠️ Ne mets PAS "package: ."
